global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    - minion01-ovh.minsys.cloud:9090
    - minion02-ovh.minsys.cloud:9090
    - minion03-ovh.minsys.cloud:9090
    - minion04-ovh.minsys.cloud:9090
    - minion05-ovh.minsys.cloud:9090
    - minion06-ovh.minsys.cloud:9090
    - minion07-ovh.minsys.cloud:9090
    - minion08-ovh.minsys.cloud:9090
    - minion09-ovh.minsys.cloud:9090
    - minion10-ovh.minsys.cloud:9090
    - minion11-ovh.minsys.cloud:9090
    - minion12-ovh.minsys.cloud:9090
    - ranch.minsys.cloud:9090
- job_name: node_exporter
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9100
    - minion01-ovh.minsys.cloud:9100
    - minion02-ovh.minsys.cloud:9100
    - minion03-ovh.minsys.cloud:9100
    - minion04-ovh.minsys.cloud:9100
    - minion05-ovh.minsys.cloud:9100
    - minion06-ovh.minsys.cloud:9100
    - minion07-ovh.minsys.cloud:9100
    - minion08-ovh.minsys.cloud:9100
    - minion09-ovh.minsys.cloud:9100
    - minion10-ovh.minsys.cloud:9100
    - minion11-ovh.minsys.cloud:9100
    - minion12-ovh.minsys.cloud:9100
    - ranch.minsys.cloud:9100
- job_name: cadvisor
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - minion01-ovh.minsys.cloud:9200
    - minion01-ovh.minsys.cloud:9200
    - minion02-ovh.minsys.cloud:9200
    - minion03-ovh.minsys.cloud:9200
    - minion04-ovh.minsys.cloud:9200
    - minion05-ovh.minsys.cloud:9200
    - minion06-ovh.minsys.cloud:9200
    - minion07-ovh.minsys.cloud:9200
    - minion08-ovh.minsys.cloud:9200
    - minion09-ovh.minsys.cloud:9200
    - minion10-ovh.minsys.cloud:9200
    - minion11-ovh.minsys.cloud:9200
    - minion12-ovh.minsys.cloud:9200
    - ranch.minsys.cloud:9200