- name: Install secure-delete tools, for managing deletion securely.
  apt: 
    pkg: secure-delete
    state: present
  become: true    

- name: Install htop, an unteractive process viewer for UNIX.
  apt: 
    pkg: htop
    state: present 
  become: true

- name: Install mtr, a network-diagnostics tool, thx Matt :-).
  apt: 
    pkg: mtr
    state: present 
  become: true

- name: Install tree, a recursive directory listing program that produces a depth indented listing of files.
  apt: 
    pkg: tree
    state: present 
  become: true

- name: Install iotop, a Disk I/Os diagnostics tool.
  apt: 
    pkg: iotop
    state: present 
  become: true

- name: Install iftop, bandwidth usage on interfaces. 
  apt: 
    pkg: iftop
    state: present 
  become: true

- name: Install sysstat, various utilities to monitor system performance and usage activity. 
  apt: 
    pkg: sysstat
    state: present 
  become: true

- name: Install whowatch, Monitor who is doing what on your Linux.
  apt: 
    pkg: whowatch
    state: present 
  become: true

- name: Install mc, GNU Midnight Commander a (the) visual file manager.
  apt: 
    pkg: mc
    state: present 
  become: true