---

- name: Create the ansible group
  group: 
    name: ansible 
    state: present
  become: true

- name: Initial admin user creation - ansible.
  user: 
    name: ansible   
    shell: /bin/bash
    groups: ansible,google-sudoers,sshusers
    append: yes
  become: true

- name: Adding the ansible public key to authorized_keys files.
  authorized_key: 
    user: ansible
    key: "{{ lookup('file', '/root/.ssh/ansible_rsa.pub') }}"
  become: true
