---

#- name: Create user group(s)
#  group:
#    name: "{{ user_usergroup }}"
#    state: present
#  become: true

#- name: Create user
#  user:
#    groups: sudo,sshusers
#    append: True
#    name: "{{ user_name }}"
#    shell: "{{ user_shell }}"
#  become: true

- name: Enable passwordless sudo
  copy:
    content: "user006 ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/user006"
    owner: "root"
    group: "root"
    mode: "0440"
#  when: user_passwordless_sudo
  become: true

