---

- name: Create the user009 group
  group: 
    name: user009 
    state: present
  become: true

- name: Initial admin user creation - user009.
  user: 
    name: user009   
    shell: /bin/bash
    createhome: yes 
    password: "{{ 'azerty123' | password_hash('sha512') }}" 
    update_password: on_creat
    home: /home/user009 
    groups: user009,sudo,sshusers
    append: yes
  register: user009
  become: true

- name: Create .ssh/ directory in user009 home directory  
  file: 
    path: /home/user009/.ssh 
    state: directory
    owner: user009
    group: user009  
    mode: "u=rw,g=rw,o=r"
  become: true

- name: Adding the user009 public key to authorized_keys files.
  authorized_key: 
    user: user009 
    key: "{{ lookup('file', '/root/.ssh/ansible_rsa') }}"
  become: true

- name: Enable passwordless sudo
  copy:
    content: "user009 ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/user009"
    owner: "root"
    group: "root"
    mode: "0440"
#  when: user_passwordless_sudo
  become: true

