---

- name: Create the user008 group
  group: 
    name: user008 
    state: present
  become: true

- name: Initial admin user creation - user008.
  user: 
    name: user008   
    shell: /bin/bash
    createhome: yes 
    home: /home/user008 
    groups: user008,sudo,sshusers
    append: yes
  register: user008
  become: true

- name: Create .ssh/ directory in user008 home directory  
  file: 
    path: /home/user008/.ssh 
    state: directory
    owner: user008
    group: user008  
    mode: "u=rw,g=rw,o=r"
  become: true

- name: Adding the user008 public key to authorized_keys files.
  authorized_key: 
    user: user008 
    key: "{{ lookup('file', '/root/.ssh/ansible_rsa') }}"
  become: true

- name: Enable passwordless sudo
  copy:
    content: "user008 ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/user008"
    owner: "root"
    group: "root"
    mode: "0440"
#  when: user_passwordless_sudo
  become: true

