---

- name: Create the user007 group
  group: 
    name: user007 
    state: present
  become: true

- name: Initial admin user creation - user007.
  user: 
    name: user007   
    shell: /bin/bash
    createhome: yes 
    home: /home/user007 
    groups: user007,sudo,sshusers
    append: yes
  register: user007
  become: true

- name: Create .ssh/ directory in user007 home directory  
  file: 
    path: /home/user007/.ssh 
    state: directory
    owner: user007
    group: user007  
    mode: "u=rw,g=rw,o=r"
  become: true

- name: Adding the user007 public key to authorized_keys files.
  authorized_key: 
    user: user007 
    key: "{{ lookup('file', '/root/.ssh/ansible_rsa') }}"
  become: true

- name: Enable passwordless sudo
  copy:
    content: "user007 ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/user007"
    owner: "root"
    group: "root"
    mode: "0440"
#  when: user_passwordless_sudo
  become: true

