---

- name: 'Basic & Standard ++MINION++ Provisionning on minsys.cloud'
  hosts: base_minion_cloud
  vars_prompt:
    - name: "confirm"
      prompt: "You really want to initiate this ++MINION++ ? yes / no"
      private: no
  pre_tasks:     
    - fail: 
        msg: "No deployment this time... aborted by user"
      when: confirm != 'yes'
  roles:
    - dist_update_upgrade
    - addgroups_initial
    - adduser_lvi
    - adduser_cso
    - motd_minsys
    - addpackages_initial
    - fail2ban
    - ssh_config
    
 