---

- name: Create the lvi group
  group: 
    name: lvi 
    state: present
  become: true

- name: Initial admin user creation - lvi.
  user: 
    name: lvi   
    shell: /bin/bash
    password: "{{ 'azerty123' | password_hash('sha512') }}" 
    update_password: on_create
    createhome: yes 
    home: /home/lvi 
    groups: lvi,sudo,admins,sshusers
    append: yes
  become: true

- name: Adding the lvi public key to authorized_keys files.
  authorized_key: 
    user: lvi 
    key: "{{ lookup('file', '/root/.ssh/lvi_pprsa.pub') }}"
  become: true

- name: User lvi will have to change password at first connection.
  shell: "chage -d 0 lvi"
  become: true

