---

- name: Run prom/node-exporter:latest Docker container
  shell: ddocker run --publish="{{ node-exporter_host_port }}":"{{ node-exporter_container_port }}" --detach=true --label=isLabel=true --label=service=nodeexporter --name="{{ node-exporter_container_prefix }}_{{ ansible_hostname }}" "{{ node-exporter_container_image }}:{{ node-exporter_container_tag }}"
  become: true
