---

- name: Create the groups -admins, sshusers- for leading users.
  group: 
    name: "{{ item }}" 
    state: present
  with_items:
    - admins
    - sshusers
  become: true

- name: Adding existing user ubuntu to group sshusers.
  user: 
    name: ubuntu 
    groups: sshusers
    append: yes
  become: true


