#!/bin/sh
echo '
---------------------------------------------------------------------------------------------------------------------------
Welcome
Ask any Q : support-technique@treeptik.fr
---------------------------------------------------------------------------------------------------------------------------      

████████╗██████╗ ███████╗███████╗██████╗ ████████╗██╗██╗  ██╗
╚══██╔══╝██╔══██╗██╔════╝██╔════╝██╔══██╗╚══██╔══╝██║██║ ██╔╝
   ██║   ██████╔╝█████╗  █████╗  ██████╔╝   ██║   ██║█████╔╝ 
   ██║   ██╔══██╗██╔══╝  ██╔══╝  ██╔═══╝    ██║   ██║██╔═██╗ 
   ██║   ██║  ██║███████╗███████╗██║        ██║   ██║██║  ██╗
   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝        ╚═╝   ╚═╝╚═╝           

--------------------------WARNING--------WARNING--------WARNING-------WARNING--------WARNING-------------------------------

This is a private computer system which is restricted to authorized individuals.
We reserve the right to view, monitor and record activity on the system without notice or permission.

If you are not an authorized user of this system or do not consent to be monitored, exit the system at this time.

--------------------------WARNING--------WARNING--------WARNING-------WARNING--------WARNING-------------------------------

Enjoy ! 

--------------------------------------------------------------------------------------------------------------------------- 
'