---
- name: Install fail2ban.
  apt: 
    pkg: fail2ban 
    state: present
  become: true

- name: Deploy fail2ban config - ssh and ssh-ddos only. 
  template: 
    src: jail.local.j2 
    dest: /etc/fail2ban/jail.local
  become: true

- name: Restart fail2ban daemon with new config
  command: systemctl restart fail2ban.service 
  become: true