---

# mkdir /opt/minsys root:root
# mkdir /opt/minsys/prometheus root:root
# mkdir /opt/minsys/prometheus/config root:root
# mkdir /opt/minsys/prometheus/data root:root


- name: Copy prometheus_blackbox configuration 
  copy: 
    src: /etc/ansible/roles/prometheus_blackbox_docker/files/prometheus.yml
    dest: /opt/minsys/prometheus/config/prometheus.yml
    owner: root 
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Run prom/prometheus:latest Docker container
  shell: docker run --publish="{{ prometheus_host_ip_tobind }}":"{{ prometheus_host_port }}":"{{ prometheus_container_port }}" --detach=true --restart=always --label=service=prometheus --name="{{ prometheus_container_prefix }}" "{{ prometheus_container_image }}:{{ prometheus_container_tag }}"
  become: true
