---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
#see "apt-cache madison docker-ce" output for a list a av. version
#17.12.0 is stable not 17.12.1 
docker_version: '17.03.02~ce-0~ubuntu'
docker_package: "docker-{{ docker_edition }}={{ docker_version }}"
docker_package_state: present
docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

