---

- name: Run prom/prometheus:latest Docker container
  shell: docker run --publish="{{ prometheus_host_ip_tobind }}":"{{ prometheus_host_port }}":"{{ prometheus_container_port }}" --detach=true --restart=always --label=service=prometheus --name="{{ prometheus_container_prefix }}" "{{ prometheus_container_image }}:{{ prometheus_container_tag }}"
  become: true
