---

- name: 'Basic & Standard ++MINION++ Provisionning on minsys.cloud' 
  hosts: pod
  roles:
    - dist_update_upgrade
    - addgroups_initial
    - adduser_lvi
    - motd_minsys
    - addpackages_initial
    - fail2ban
    - ssh_config
    
 