---

- name: 'Deploy base config to minsys.cloud' 
  hosts: pod
  roles:
    - dist_update_upgrade
    - addgroups_initial
    - adduser_ansible_gcp
    - adduser_lvi
    - addpackages_initial
    - fail2ban
    - ssh_config
    - motd_minsys
    - install_docker-ce
    - node-exporter_docker
    - cadvisor_docker
    - prometheus_node_docker
    - nginx_initial