---

- name: 'TEST01-GCP' 
  hosts: pod
  roles:
    - dist_update_upgrade
    - addgroups_initial
    - adduser_ansible_gcp
    - adduser_lvi
    - addpackages_initial
    - fail2ban
    - ssh_config
    - motd_minsys
    - nginx_initial
    - initweb