---

- name: 'Test 01' 
  hosts: pod
  roles:
    - dist_update_upgrade
    - addgroups_initial
    - adduser_ansible
    - adduser_lvi
    - motd_minsys
#    - addpackages_initial
#    - fail2ban
    - ssh_config
#    - install_docker-ce
#    - node-exporter_docker
#    - cadvisor_docker
#    - prometheus_node_docker
#    - nginx_initial