---

- name: 'Deploy OVH minion(s) as rancher registered host(s) on a K8s environment' 
  hosts: pod
  roles:
    - dist_update_upgrade
    - addgroups_initial
    - adduser_lvi
    - adduser_cso
    - motd_minsys
    - addpackages_initial
    - fail2ban
    - ssh_config
    - install_docker-ce
    - node-exporter_docker
    - cadvisor_docker
    - prometheus_node_docker
    - is_rancher_host
    